In [60]:
import pandas as pd
import numpy as np
import warnings
import datetime

In [2]:
warnings.filterwarnings("ignore")

In [3]:
order_df=pd.read_csv('~/Oskar/customer-analysis/olist_orders_dataset.csv')

In [4]:
order_items_df=pd.read_csv('~/Oskar/customer-analysis/olist_order_items_dataset.csv')

In [5]:
items_df=pd.read_csv('~/Oskar/customer-analysis/olist_products_dataset.csv')

In [6]:
payments_df=pd.read_csv('~/Oskar/customer-analysis/olist_order_payments_dataset.csv')

In [7]:
customer_df=pd.read_csv('~/Oskar/customer-analysis/olist_customers_dataset.csv')

### Orders characteristics

dimension:

In [8]:
order_df.shape

(99441, 8)

columns:

In [9]:
list(order_df.columns)

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date']

countin nulls:

In [10]:
order_df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

### Order-items characteristic

dimension:

In [11]:
order_items_df.shape

(112650, 7)

columns:

In [12]:
list(order_items_df.columns)

['order_id',
 'order_item_id',
 'product_id',
 'seller_id',
 'shipping_limit_date',
 'price',
 'freight_value']

counting nulls:

In [13]:
order_items_df.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

### Items characteristics:

dimension:

In [14]:
items_df.shape

(32951, 9)

columns:

In [15]:
list(items_df.columns)

['product_id',
 'product_category_name',
 'product_name_lenght',
 'product_description_lenght',
 'product_photos_qty',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm']

counting nulls:

In [16]:
items_df.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [17]:
items_df['product_category_name'].value_counts()[0:20]

cama_mesa_banho                      3029
esporte_lazer                        2867
moveis_decoracao                     2657
beleza_saude                         2444
utilidades_domesticas                2335
automotivo                           1900
informatica_acessorios               1639
brinquedos                           1411
relogios_presentes                   1329
telefonia                            1134
bebes                                 919
perfumaria                            868
papelaria                             849
fashion_bolsas_e_acessorios           849
cool_stuff                            789
ferramentas_jardim                    753
pet_shop                              719
eletronicos                           517
construcao_ferramentas_construcao     400
eletrodomesticos                      370
Name: product_category_name, dtype: int64

### Customers characteristics

dimension:

In [18]:
customer_df.shape

(99441, 5)

In [19]:
list(customer_df.columns)

['customer_id',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state']

In [20]:
customer_df['customer_city'].value_counts()

sao paulo                 15540
rio de janeiro             6882
belo horizonte             2773
brasilia                   2131
curitiba                   1521
campinas                   1444
porto alegre               1379
salvador                   1245
guarulhos                  1189
sao bernardo do campo       938
niteroi                     849
santo andre                 797
osasco                      746
santos                      713
goiania                     692
sao jose dos campos         691
fortaleza                   654
sorocaba                    633
recife                      613
florianopolis               570
jundiai                     565
ribeirao preto              510
belem                       447
nova iguacu                 442
barueri                     433
juiz de fora                427
contagem                    426
sao goncalo                 409
mogi das cruzes             383
vitoria                     380
                          ...
cotipora                      1
venda branca                  1
natividade da serra           1
pitanga de estrada            1
brejo do cruz                 1
nova guarita                  1
anage                         1
curralinho                    1
andre da rocha                1
itanhem                       1
pirambu                       1
ibiracatu                     1
alto bela vista               1
varzedo                       1
bodo                          1
castanheiras                  1
sao geraldo do baguari        1
sao lourenco do piaui         1
nova crixas                   1
lavrinhas                     1
agua preta                    1
alpestre                      1
lagoa do mato                 1
mucambo                       1
almino afonso                 1
pocoes de paineiras           1
turvelandia                   1
vicente dutra                 1
santa maria do herval         1
cascalho rico                 1
Name: customer_city, dtype: int64

### Payments characteristics

dimension:

In [21]:
payments_df.shape

(103886, 5)

columns:

In [22]:
list(payments_df.columns)

['order_id',
 'payment_sequential',
 'payment_type',
 'payment_installments',
 'payment_value']

counting nulls:

In [23]:
payments_df.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

unique order id's:

In [24]:
len(payments_df['order_id'].unique())

99440

payment types:

In [25]:
payments_df['payment_type'].value_counts()

credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: payment_type, dtype: int64

In [26]:
payments_df[0:10]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
5,298fcdf1f73eb413e4d26d01b25bc1cd,1,credit_card,2,96.12
6,771ee386b001f06208a7419e4fc1bbd7,1,credit_card,1,81.16
7,3d7239c394a212faae122962df514ac7,1,credit_card,3,51.84
8,1f78449c87a54faf9e96e88ba1491fa9,1,credit_card,6,341.09
9,0573b5e23cbd798006520e1d5b4c6714,1,boleto,1,51.95

### Aggregating values and number of products per order

Prices of the ordered products are in order_item datset. Let's calculate sum and mean values of products, and number of products per order, and then add it to orders dataset:

In [27]:
order_items_df['total_value']=order_items_df['price']+order_items_df['freight_value']

In [28]:
order_agg1=order_items_df[['order_id','price','freight_value','total_value']].groupby('order_id').sum().reset_index()

In [29]:
order_agg1.columns=['order_id','sum_price','sum_freight_value','sum_total_value']

In [30]:
order_agg2=order_items_df[['order_id','price','freight_value','total_value']].groupby('order_id').mean().reset_index()

In [31]:
order_agg2.columns=['order_id','avg_price','avg_freight_value','avg_total_value']

In [32]:
order_df=order_df.merge(order_agg1,on='order_id')

In [33]:
order_df=order_df.merge(order_agg2,on='order_id')

In [34]:
order_df['num_items']=order_df['sum_total_value']/order_df['avg_total_value']

In [35]:
list(order_df.columns)

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'sum_price',
 'sum_freight_value',
 'sum_total_value',
 'avg_price',
 'avg_freight_value',
 'avg_total_value',
 'num_items']

### Aggregating most-common product categories per order

We would like to aggregate information about product categories per order. We can do it by creating binary features corresponding to the most common product names and aggregate those features per orders:

In [36]:
most_common_categ=items_df['product_category_name'].value_counts().reset_index()[0:10]

In [37]:
most_common_categ

                    index  product_category_name
0         cama_mesa_banho                   3029
1           esporte_lazer                   2867
2        moveis_decoracao                   2657
3            beleza_saude                   2444
4   utilidades_domesticas                   2335
5              automotivo                   1900
6  informatica_acessorios                   1639
7              brinquedos                   1411
8      relogios_presentes                   1329
9               telefonia                   1134

In [38]:
most_common_categ_names=list(most_common_categ['index'])

In [39]:
most_common_categ_names

['cama_mesa_banho',
 'esporte_lazer',
 'moveis_decoracao',
 'beleza_saude',
 'utilidades_domesticas',
 'automotivo',
 'informatica_acessorios',
 'brinquedos',
 'relogios_presentes',
 'telefonia']

In [40]:
produc_category_bin=pd.get_dummies(items_df['product_category_name'])

In [41]:
most_common_bin=produc_category_bin[most_common_categ_names]

In [42]:
items_df.columns

Index([u'product_id', u'product_category_name', u'product_name_lenght',
       u'product_description_lenght', u'product_photos_qty',
       u'product_weight_g', u'product_length_cm', u'product_height_cm',
       u'product_width_cm'],
      dtype='object')

In [43]:
most_common_bin['product_id']=items_df['product_id']

In [44]:
order_items_df=order_items_df.merge(most_common_bin,on='product_id')

In [45]:
order_items_df.columns

Index([u'order_id', u'order_item_id', u'product_id', u'seller_id',
       u'shipping_limit_date', u'price', u'freight_value', u'total_value',
       u'cama_mesa_banho', u'esporte_lazer', u'moveis_decoracao',
       u'beleza_saude', u'utilidades_domesticas', u'automotivo',
       u'informatica_acessorios', u'brinquedos', u'relogios_presentes',
       u'telefonia'],
      dtype='object')

In [46]:
order_items_df_agg=order_items_df[['order_id']+most_common_categ_names].groupby('order_id').sum().reset_index()

In [47]:
order_items_df_agg

,order_id,cama_mesa_banho,esporte_lazer,moveis_decoracao,beleza_saude,utilidades_domesticas,automotivo,informatica_acessorios,brinquedos,relogios_presentes,telefonia
0,00010242fe8c5a6d1ba2dd792cb16214,0,0,0,0,0,0,0,0,0,0
1,00018f77f2f0320c557190d7a144bdd3,0,0,0,0,0,0,0,0,0,0
2,000229ec398224ef6ca0657da4fc703e,0,0,1,0,0,0,0,0,0,0
3,00024acbcdf0a6daa1e931b038114c75,0,0,0,0,0,0,0,0,0,0
4,00042b26cf59d7ce69dfabb4e55b4fd9,0,0,0,0,0,0,0,0,0,0
5,00048cc3ae777c65dbb7d2a0634bc1ea,0,0,0,0,1,0,0,0,0,0
6,00054e8431b9d7675808bcb819fb4a32,0,0,0,0,0,0,0,0,0,1
7,000576fe39319847cbb9d288c5617fa6,0,0,0,0,0,0,0,0,0,0
8,0005a1a1728c9d785b8e2b08b904576c,0,0,0,1,0,0,0,0,0,0
9,0005f50442cb953dcd1d21e1fb923495,0,0,0,0,0,0,0,0,0,0
10,00061f2a7bc09da83e415a52dc8a4af1,0,0,0,1,0,0,0,0,0,0
11,00063b381e2406b52ad429470734ebd5,0,0,0,0,0,0,0,0,0,0
12,0006ec9db01a64e59a68b2c340bf65a7,1,0,0,0,0,0,0,0,0,0
13,0008288aa423d2a3f00fcb17cd7d8719,0,0,0,0,0,0,0,0,0,0
14,0009792311464db532ff765bf7b182ae,0,1,0,0,0,0,0,0,0,0
15,0009c9a17f916a706d71784483a5d643,0,0,0,0,0,0,0,0,0,0
16,000aed2e25dbad2f9ddb70584c5a2ded,0,0,0,0,0,0,0,0,0,0
17,000c3e6612759851cc3cbb4b83257986,0,1,0,0,0,0,0,0,0,0
18,000e562887b1f2006d75e0be9558292e,0,0,0,0,0,0,0,0,0,0
19,000e63d38ae8c00bbcb5a30573b99628,1,0,0,0,0,0,0,0,0,0
20,000e906b789b55f64edcb1f84030f90d,0,0,0,0,0,0,0,0,0,1
21,000f25f4d72195062c040b12dce9a18a,0,0,0,0,0,0,0,0,0,0
22,001021efaa8636c29475e7734483457d,0,0,0,0,0,0,0,0,0,0
23,0010b2e5201cc5f1ae7e9c6cc8f5bd00,0,0,0,0,0,0,0,0,0,0
24,00119ff934e539cf26f92b9ef0cdfed8,0,1,0,0,0,0,0,0,0,0
25,0011d82c4b53e22e84023405fb467e57,0,0,0,0,0,0,0,0,0,0
26,00125cb692d04887809806618a2a145f,0,0,1,0,0,0,0,0,0,0
27,00130c0eee84a3d909e75bc08c5c3ca1,0,0,0,0,0,0,0,0,0,0
28,0013503b13da1eac686219390b7d641b,0,0,1,0,0,0,0,0,0,0
29,00137e170939bba5a3134e2386413108,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
98636,ffec1a6d35149778ec575d5048d44db8,0,0,0,1,0,0,0,0,0,0
98637,ffecd5a79a0084f6a592288c67e3c298,0,0,0,0,0,0,0,0,0,0
98638,ffed7e90414c1477a6b92554661d465f,0,0,0,0,0,0,1,0,0,0
98639,ffee31fb4b5e35c9123608015637c495,0,0,1,0,0,0,0,0,0,0
98640,ffeeb911d070bea3dd20bd5fd01da5e8,0,0,1,0,0,0,0,0,0,0
98641,ffef98cd5ecdc992fefbd967549520dd,0,0,0,0,0,0,0,0,0,0
98642,ffef9e1de5dd07b397b373f9bb72cccf,0,0,0,0,1,0,0,0,0,0
98643,ffefb169ddf34cecc0622a6d3cc387f8,0,0,0,0,0,0,0,0,0,0
98644,fff0db5573c78c1cb5a2b68a2bbd8d4a,0,0,0,1,0,0,0,0,0,0
98645,fff1e3e76b816bfe8ef16678cc53c643,0,0,0,0,0,0,0,0,0,0
98646,fff2cdc825f9fc0ba3c04227cfa02303,0,0,0,0,0,0,0,0,0,1
98647,fff2e9e3aa8644e19710216b4ef53ab2,1,0,0,0,0,0,0,0,0,0
98648,fff3983dfa3c5a0d752d8d17baa406a0,0,0,0,0,0,0,0,0,0,0
98649,fff60e5408a9dd1e92ee30023052af30,0,1,0,0,0,0,0,0,0,0
98650,fff6889749958e42b47a7977a4cf0ea0,0,0,0,0,0,0,0,0,0,0
98651,fff6b8ca971f8e3ec822e99d0f2d3d21,0,0,0,0,0,0,0,0,0,1
98652,fff7c4452f050315db1b3f24d9df5fcd,0,0,0,0,0,0,0,0,1,0
98653,fff8286f77788ab8b55b2e5747fa7dd8,0,0,0,0,0,0,0,0,0,1
98654,fff8287bbae429a99bb7e8c21d151c41,0,0,0,0,0,0,2,0,0,0
98655,fff90cdcb3b2e6cfb397d05d562fd3fe,0,0,1,0,0,0,0,0,0,0
98656,fffa82886406ccf10c7b4e35c4ff2788,0,1,0,0,0,0,0,0,0,0
98657,fffb0b1a50e65c449020434fa835e078,0,0,0,0,0,0,0,0,0,0
98658,fffb2ef8874127f75b52b643880fd7e0,1,0,0,0,0,0,0,0,0,0
98659,fffb9224b6fc7c43ebb0904318b10b5f,0,0,0,0,0,0,0,0,4,0
98660,fffbee3b5462987e66fb49b1c5411df2,0,0,0,0,0,0,0,0,0,0
98661,fffc94f6ce00a00581880bf54a75a037,0,0,0,0,1,0,0,0,0,0
98662,fffcd46ef2263f404302a634eb57f7eb,0,0,0,0,0,0,1,0,0,0
98663,fffce4705a9662cd70adb13d4a31832d,0,1,0,0,0,0,0,0,0,0
98664,fffe18544ffabc95dfada21779c9644f,0,0,0,0,0,0,1,0,0,0
98665,fffe41c64501cc87c801fd61db3f6244,1,0,0,0,0,0,0,0,0,0

In [48]:
order_df=order_df.merge(order_items_df_agg,on='order_id')

In [49]:
list(order_df.columns)

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'sum_price',
 'sum_freight_value',
 'sum_total_value',
 'avg_price',
 'avg_freight_value',
 'avg_total_value',
 'num_items',
 'cama_mesa_banho',
 'esporte_lazer',
 'moveis_decoracao',
 'beleza_saude',
 'utilidades_domesticas',
 'automotivo',
 'informatica_acessorios',
 'brinquedos',
 'relogios_presentes',
 'telefonia']

### Aggregating payments data per order

In [50]:
payments_df[0:10]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
5,298fcdf1f73eb413e4d26d01b25bc1cd,1,credit_card,2,96.12
6,771ee386b001f06208a7419e4fc1bbd7,1,credit_card,1,81.16
7,3d7239c394a212faae122962df514ac7,1,credit_card,3,51.84
8,1f78449c87a54faf9e96e88ba1491fa9,1,credit_card,6,341.09
9,0573b5e23cbd798006520e1d5b4c6714,1,boleto,1,51.95

In [51]:
payments_df['payment_type'].unique()

array(['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined'], dtype=object)

In [52]:
payments_df['card_payment']=payments_df['payment_type'].isin(['credit_card','debit_card']).astype('int')

In [53]:
payments_df['voucher_payment']=payments_df['payment_type'].isin(['voucher','boleto']).astype('int')

In [54]:
payments_agg1=payments_df[['order_id','payment_installments']].groupby('order_id').sum().reset_index()

In [55]:
payments_agg2=payments_df[['order_id','card_payment','voucher_payment']].groupby('order_id').mean().reset_index()

In [56]:
order_df.columns

Index([u'order_id', u'customer_id', u'order_status',
       u'order_purchase_timestamp', u'order_approved_at',
       u'order_delivered_carrier_date', u'order_delivered_customer_date',
       u'order_estimated_delivery_date', u'sum_price', u'sum_freight_value',
       u'sum_total_value', u'avg_price', u'avg_freight_value',
       u'avg_total_value', u'num_items', u'cama_mesa_banho', u'esporte_lazer',
       u'moveis_decoracao', u'beleza_saude', u'utilidades_domesticas',
       u'automotivo', u'informatica_acessorios', u'brinquedos',
       u'relogios_presentes', u'telefonia'],
      dtype='object')

In [57]:
order_df=order_df.merge(payments_agg1, on='order_id')

In [58]:
order_df=order_df.merge(payments_agg2, on='order_id')

In [74]:
order_df['order_delivered_customer_date']=order_df['order_delivered_customer_date'].map(lambda x:)

TypeError: 'numpy.ndarray' object is not callable

In [69]:
order_df['purchase_deliver_timediff']=order_df[['order_delivered_customer_date',
        'order_purchase_timestamp']].apply(lambda x: x.order_delivered_customer_date-x.order_purchase_timestamp)

AttributeError: ("'Series' object has no attribute 'order_delivered_customer_date'", u'occurred at index order_delivered_customer_date')

In [70]:
order_df['purchase_deliver_timediff']=order_df['order_delivered_customer_date']-order_df['order_purchase_timestamp']

TypeError: unsupported operand type(s) for -: 'str' and 'str'

### Aggregating data per customer

In [67]:
cust_agg1=order_df[['customer_id','sum_price','sum_freight_value','sum_total_value',
            'num_items','payment_installments']+most_common_categ_names].groupby('customer_id').sum().reset_index()

In [68]:
cust_agg2=order_df[['customer_id','sum_price','sum_freight_value','sum_total_value',
                   'avg_price','avg_freight_value','avg_total_value',
                   'card_payment','voucher_payment']].groupby('customer_id').mean().reset_index()

In [82]:
cust_agg3=order_df['customer_id'].value_counts().reset_index()

In [86]:
cust_agg3['customer_id'].unique()

array([1])

In [70]:
most_common_categ_names2=map(lambda x: 'sum_'+x, most_common_categ_names)

cust_agg1.columns=['customer_id','sum_price','sum_freight_value',
                   'sum_total_value','sum_items','sum_installments']+most_common_categ_names2

In [71]:
cust_agg2.columns=['customer_id','avg_order_price','avg_order_freight_price','avg_order_value',
                   'avg_product_price','avg_product_freight_price','avg_product_value',
                  'avg_card_payment','avg_voucher_payment']

In [72]:
customer_df=customer_df.merge(cust_agg1,on='customer_id')

In [73]:
customer_df=customer_df.merge(cust_agg2,on='customer_id')

In [74]:
list(customer_df.columns)

['customer_id',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state',
 'sum_price',
 'sum_freight_value',
 'sum_total_value',
 'sum_items',
 'payment_installments',
 'sum_cama_mesa_banho',
 'sum_esporte_lazer',
 'sum_moveis_decoracao',
 'sum_beleza_saude',
 'sum_utilidades_domesticas',
 'sum_automotivo',
 'sum_informatica_acessorios',
 'sum_brinquedos',
 'sum_relogios_presentes',
 'sum_telefonia',
 'avg_order_price',
 'avg_order_freight_price',
 'avg_order_value',
 'avg_product_price',
 'avg_product_freight_price',
 'avg_product_value',
 'card_payment',
 'voucher_payment']

In [25]:
order_df['purchase_deliver_timediff']=order_df['order_delivered_customer_date']-order_df['order_purchase_timestamp']

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [26]:
order_df[['order_delivered_customer_date','order_purchase_timestamp']]

      order_delivered_customer_date order_purchase_timestamp
0               2017-10-10 21:25:13      2017-10-02 10:56:33
1               2018-08-07 15:27:45      2018-07-24 20:41:37
2               2018-08-17 18:06:29      2018-08-08 08:38:49
3               2017-12-02 00:28:42      2017-11-18 19:28:06
4               2018-02-16 18:17:02      2018-02-13 21:18:39
5               2017-07-26 10:57:55      2017-07-09 21:57:05
6                               NaN      2017-04-11 12:22:08
7               2017-05-26 12:55:51      2017-05-16 13:10:30
8               2017-02-02 14:08:10      2017-01-23 18:29:09
9               2017-08-16 17:14:30      2017-07-29 11:55:02
10              2017-05-29 11:18:31      2017-05-16 19:41:10
11              2017-07-19 14:04:48      2017-07-13 19:58:11
12              2018-06-19 12:05:52      2018-06-07 10:06:19
13              2018-07-30 15:52:25      2018-07-25 17:44:10
14              2018-03-12 23:36:26      2018-03-01 14:14:28
15              2018-06-21 15:34:32      2018-06-07 19:03:12
16              2018-01-20 01:38:59      2018-01-02 19:00:43
17              2018-01-08 22:36:36      2017-12-26 23:41:31
18              2017-11-27 18:28:00      2017-11-21 00:03:41
19              2017-11-08 22:22:00      2017-10-26 15:54:26
20              2017-10-09 22:23:46      2017-09-18 14:31:30
21              2018-03-19 18:08:32      2018-03-15 08:52:40
22              2018-02-08 16:13:46      2018-02-03 20:37:35
23              2018-01-26 17:32:38      2018-01-08 07:55:29
24              2018-08-13 18:24:27      2018-08-09 11:44:40
25              2018-03-21 22:03:54      2018-02-20 23:46:53
26              2018-06-16 15:20:55      2018-06-04 00:00:13
27              2018-03-21 14:41:50      2018-03-12 01:50:26
28              2018-05-16 20:56:24      2018-05-02 11:45:38
29              2018-03-27 23:29:14      2018-02-25 13:50:30
...                             ...                      ...
98636           2017-09-14 15:49:47      2017-09-03 20:52:34
98637           2018-07-24 22:46:38      2018-07-22 16:58:38
98638           2017-12-05 18:38:40      2017-11-26 19:42:22
98639           2018-04-06 21:32:35      2018-04-01 16:13:26
98640           2017-08-23 15:36:29      2017-08-10 21:21:07
98641           2018-06-07 13:22:19      2018-06-03 18:44:31
98642           2018-03-05 18:56:39      2018-02-07 12:09:45
98643           2017-12-13 20:34:50      2017-11-30 17:54:28
98644           2017-10-06 16:58:25      2017-10-02 08:45:35
98645           2017-06-19 19:19:30      2017-06-07 11:02:37
98646           2017-07-19 22:10:03      2017-07-05 15:55:19
98647           2018-06-04 23:54:32      2018-05-25 17:05:17
98648           2017-11-21 17:06:59      2017-10-12 20:54:11
98649           2017-12-02 16:48:46      2017-11-21 20:18:03
98650           2018-04-11 00:48:31      2018-03-21 19:47:18
98651           2017-05-22 18:05:56      2017-05-15 09:46:26
98652           2018-05-18 17:18:29      2018-05-12 13:42:24
98653           2018-07-03 19:48:54      2018-06-22 20:53:29
98654           2017-11-08 16:08:56      2017-11-05 16:17:53
98655           2018-03-13 18:54:32      2018-03-04 22:48:38
98656           2017-11-10 17:57:22      2017-10-27 15:21:00
98657           2018-01-26 15:45:14      2017-12-20 09:52:41
98658           2017-10-20 20:25:45      2017-10-04 19:57:37
98659           2017-02-07 13:15:25      2017-01-27 00:30:03
98660           2017-03-06 11:08:08      2017-02-23 09:05:12
98661           2017-03-17 15:08:01      2017-03-09 09:54:05
98662           2018-02-28 17:37:56      2018-02-06 12:58:58
98663           2017-09-21 11:24:17      2017-08-27 14:46:43
98664           2018-01-25 23:32:54      2018-01-08 21:28:27
98665           2018-03-16 13:08:30      2018-03-08 20:57:30

[98666 rows x 2 columns]

In [27]:
def date_dff(x):
    diff = x.order_delivered_customer_date-x.order_purchase_timestamp
    return(diff.days)
    
order_df[['order_delivered_customer_date','order_purchase_timestamp']].apply(lambda x: 
            x.order_delivered_customer_date-x.order_purchase_timestamp)

AttributeError: ("'Series' object has no attribute 'order_delivered_customer_date'", u'occurred at index order_delivered_customer_date')

### Aggregating data per payments and merging with orders

In [46]:
payments_df

,order_id,payment_sequential,payment_type,payment_installments,payment_value,card_payment
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33,1
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39,1
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71,1
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78,1
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45,1
5,298fcdf1f73eb413e4d26d01b25bc1cd,1,credit_card,2,96.12,1
6,771ee386b001f06208a7419e4fc1bbd7,1,credit_card,1,81.16,1
7,3d7239c394a212faae122962df514ac7,1,credit_card,3,51.84,1
8,1f78449c87a54faf9e96e88ba1491fa9,1,credit_card,6,341.09,1
9,0573b5e23cbd798006520e1d5b4c6714,1,boleto,1,51.95,0
10,d88e0d5fa41661ce03cf6cf336527646,1,credit_card,8,188.73,1
11,2480f727e869fdeb397244a21b721b67,1,credit_card,1,141.90,1
12,616105c9352a9668c38303ad44e056cd,1,credit_card,1,75.78,1
13,cf95215a722f3ebf29e6bbab87a29e61,1,credit_card,5,102.66,1
14,769214176682788a92801d8907fa1b40,1,credit_card,4,105.28,1
15,12e5cfe0e4716b59afb0e0f4a3bd6570,1,credit_card,10,157.45,1
16,61059985a6fc0ad64e95d9944caacdad,1,credit_card,1,132.04,1
17,79da3f5fe31ad1e454f06f95dc032ad5,1,credit_card,1,98.94,1
18,8ac09207f415d55acff302df7d6a895c,1,credit_card,4,244.15,1
19,b2349a3f20dfbeef62e7b31baa22f84b,1,credit_card,3,136.71,1
20,5a1f6d22f7dfb061ef29216b9af687a1,1,credit_card,4,47.69,1
21,4214cda550ece8ee66441f459dc33a8c,1,credit_card,2,170.57,1
22,adfbf6c2a620196f9a3ec747491c72b7,1,credit_card,4,67.50,1
23,4d680edbaa7d3d9bed69532957368a03,1,credit_card,10,353.09,1
24,8cd68144cdb62dc0d60848cf8616d2a4,1,boleto,1,330.66,0
25,5cfd514482e22bc992e7693f0e3e8df7,2,voucher,1,45.17,0
26,d0a945f85ba1074b60aac97ade7e240e,1,credit_card,2,541.00,1
27,c39414c195d0f94c9d9c35e7c6ed4f1a,1,credit_card,2,139.22,1
28,5d9c5817e278892b7498d90bfa28ade8,1,credit_card,2,290.16,1
29,b69b9260e79a0da00e15f48de1bd2524,1,boleto,1,283.34,0
...,...,...,...,...,...,...
103856,aba440032be16b32505c6e14bb755b0c,1,credit_card,1,36.11,1
103857,31001a77165dd554fcc32640defe98a1,1,credit_card,3,104.85,1
103858,ba1e49527baf8b4ad4b501e9dcaa9f6d,1,credit_card,1,124.52,1
103859,e0657085c2b6297a32f39efa200cdf72,1,credit_card,1,26.37,1
103860,31bc09fdbd701a7a4f9b55b5955b8687,6,voucher,1,77.99,0
103861,691688405bcee3ff9023639514498962,1,credit_card,1,356.53,1
103862,807f4ef550f104708e2190eca7e4c37a,1,credit_card,3,205.71,1
103863,4b186efcda6f283e9c4a71332f6d3ad0,1,credit_card,1,57.51,1
103864,c11717d999ffc510a6441df946f0a94d,1,credit_card,9,96.90,1
103865,f593228a7a25e9633ff78a4ce0d0d4cc,1,credit_card,8,165.80,1
103866,387c2c33e495538e94878a500bf8e6d5,1,credit_card,1,87.58,1
103867,d5639d8a973cec351be75a3186835068,1,boleto,1,160.89,0
103868,0020262c8a370bd5a174ea6a2a267321,1,credit_card,2,100.55,1
103869,c9b01bef18eb84888f0fd071b8413b38,1,credit_card,6,238.16,1
103870,9ac048d7ffebba67d54456aa9ec07d7e,1,credit_card,1,60.69,1
103871,20824837882dd673707e0adfcaec1bc1,1,credit_card,1,84.23,1
103872,38d11c87fc409de31e930084abb0c7a4,1,credit_card,7,91.03,1
103873,40ec2cf5cb1eb0bf1ea2b117552fecb5,1,credit_card,2,90.28,1
103874,d41f1036712e18ee525939d08b7a1c98,1,credit_card,1,3.57,1
103875,60aed0a4eba0e424eb3cac85017fd752,1,credit_card,10,170.14,1
103876,0872d0faafe0cb56e6f2c594cca1522c,1,credit_card,2,127.92,1
103877,3531718b24dfd5022fb0d101e10e33b9,1,credit_card,1,194.11,1
103878,2e3d96522c8c378d4135c12a65c977aa,1,credit_card,4,47.62,1
103879,c45067032fd84f4cf408730ff5205568,1,credit_card,2,198.94,1
103880,7159096c5aa9be77f7f0c26c01ee9793,1,credit_card,4,280.65,1
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31,0
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80,1
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77,1
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54,1
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58,0

In [38]:
payments_df.columns

Index([u'order_id', u'payment_sequential', u'payment_type',
       u'payment_installments', u'payment_value'],
      dtype='object')

In [42]:
payments_df['payment_type'].value_counts()

credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: payment_type, dtype: int64

In [45]:
payments_df['card_payment']=np.where(
    (payments_df['payment_type']=='credit_card')|(payments_df['payment_type']=='debit_card'),1,0)

In [47]:
payments_df['non_card_payment']=np.where(payments_df['card_payment']==1,0,1)

In [50]:
payments_agg=payments_df[['order_id','payment_installments',
                          'card_payment','non_card_payment']].groupby('order_id').sum().reset_index()

In [51]:
payments_agg

,order_id,payment_installments,card_payment,non_card_payment
0,00010242fe8c5a6d1ba2dd792cb16214,2,1,0
1,00018f77f2f0320c557190d7a144bdd3,3,1,0
2,000229ec398224ef6ca0657da4fc703e,5,1,0
3,00024acbcdf0a6daa1e931b038114c75,2,1,0
4,00042b26cf59d7ce69dfabb4e55b4fd9,3,1,0
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,0,1
6,00054e8431b9d7675808bcb819fb4a32,1,1,0
7,000576fe39319847cbb9d288c5617fa6,10,1,0
8,0005a1a1728c9d785b8e2b08b904576c,3,1,0
9,0005f50442cb953dcd1d21e1fb923495,1,1,0
10,00061f2a7bc09da83e415a52dc8a4af1,3,1,0
11,00063b381e2406b52ad429470734ebd5,5,1,0
12,0006ec9db01a64e59a68b2c340bf65a7,4,1,0
13,0008288aa423d2a3f00fcb17cd7d8719,1,0,1
14,0009792311464db532ff765bf7b182ae,1,0,1
15,0009c9a17f916a706d71784483a5d643,6,1,0
16,000aed2e25dbad2f9ddb70584c5a2ded,1,1,0
17,000c3e6612759851cc3cbb4b83257986,1,0,1
18,000e562887b1f2006d75e0be9558292e,4,1,0
19,000e63d38ae8c00bbcb5a30573b99628,1,1,0
20,000e906b789b55f64edcb1f84030f90d,3,1,0
21,000f25f4d72195062c040b12dce9a18a,1,1,0
22,001021efaa8636c29475e7734483457d,3,1,0
23,0010b2e5201cc5f1ae7e9c6cc8f5bd00,3,1,0
24,0010dedd556712d7bb69a19cb7bbd37a,1,0,1
25,00119ff934e539cf26f92b9ef0cdfed8,6,1,0
26,0011d82c4b53e22e84023405fb467e57,2,1,0
27,00125cb692d04887809806618a2a145f,1,1,0
28,00130c0eee84a3d909e75bc08c5c3ca1,1,0,1
29,0013503b13da1eac686219390b7d641b,1,0,1
...,...,...,...,...
99410,ffec1a6d35149778ec575d5048d44db8,1,0,1
99411,ffecd5a79a0084f6a592288c67e3c298,1,1,0
99412,ffed7e90414c1477a6b92554661d465f,5,1,0
99413,ffee31fb4b5e35c9123608015637c495,2,1,0
99414,ffeeb911d070bea3dd20bd5fd01da5e8,5,1,0
99415,ffef98cd5ecdc992fefbd967549520dd,1,0,1
99416,ffef9e1de5dd07b397b373f9bb72cccf,5,1,0
99417,ffefb169ddf34cecc0622a6d3cc387f8,3,1,0
99418,fff0db5573c78c1cb5a2b68a2bbd8d4a,2,1,0
99419,fff1e3e76b816bfe8ef16678cc53c643,7,1,0
99420,fff2cdc825f9fc0ba3c04227cfa02303,1,0,1
99421,fff2e9e3aa8644e19710216b4ef53ab2,1,0,1
99422,fff3983dfa3c5a0d752d8d17baa406a0,3,1,0
99423,fff60e5408a9dd1e92ee30023052af30,1,1,0
99424,fff6889749958e42b47a7977a4cf0ea0,10,1,0
99425,fff6b8ca971f8e3ec822e99d0f2d3d21,3,1,0
99426,fff7c4452f050315db1b3f24d9df5fcd,1,1,0
99427,fff8286f77788ab8b55b2e5747fa7dd8,4,1,0
99428,fff8287bbae429a99bb7e8c21d151c41,4,1,0
99429,fff90cdcb3b2e6cfb397d05d562fd3fe,1,1,0
99430,fffa82886406ccf10c7b4e35c4ff2788,7,1,0
99431,fffb0b1a50e65c449020434fa835e078,1,1,0
99432,fffb2ef8874127f75b52b643880fd7e0,1,0,1
99433,fffb9224b6fc7c43ebb0904318b10b5f,1,0,1
99434,fffbee3b5462987e66fb49b1c5411df2,3,1,0
99435,fffc94f6ce00a00581880bf54a75a037,1,0,1
99436,fffcd46ef2263f404302a634eb57f7eb,1,0,1
99437,fffce4705a9662cd70adb13d4a31832d,3,1,0
99438,fffe18544ffabc95dfada21779c9644f,3,1,0
99439,fffe41c64501cc87c801fd61db3f6244,1,1,0

### Merging orders with customers

In [35]:
order_df.columns

Index([u'order_id', u'customer_id', u'order_status',
       u'order_purchase_timestamp', u'order_approved_at',
       u'order_delivered_carrier_date', u'order_delivered_customer_date',
       u'order_estimated_delivery_date'],
      dtype='object')

In [36]:
customer_df.columns

Index([u'customer_id', u'customer_unique_id', u'customer_zip_code_prefix',
       u'customer_city', u'customer_state'],
      dtype='object')

In [30]:
customer_order_df=customer_df.merge(order_df,on='customer_id')

In [31]:
customer_order_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05 00:00:00
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06 00:00:00
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13 00:00:00
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10 00:00:00
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15 00:00:00
5,879864dab9bc3047522c92c82e1212b8,4c93744516667ad3b8f1fb645a3116a4,89254,jaragua do sul,SC,5741ea1f91b5fbab2bd2dc653a5b5099,delivered,2017-09-14 18:14:31,2017-09-14 18:25:11,2017-09-18 21:27:40,2017-09-28 17:32:43,2017-10-04 00:00:00
6,fd826e7cf63160e536e0908c76c3f441,addec96d2e059c80c30fe6871d30d177,4534,sao paulo,SP,36e694cf4cbc2a4803200c35e84abdc4,delivered,2018-02-19 14:38:35,2018-02-19 14:50:37,2018-02-20 00:03:39,2018-02-20 16:25:51,2018-03-05 00:00:00
7,5e274e7a0c3809e14aba7ad5aae0d407,57b2a98a409812fe9618067b6b8ebe4f,35182,timoteo,MG,1093c8304c7a003280dd34598194913d,delivered,2017-11-16 19:29:02,2017-11-16 19:55:41,2017-11-22 16:46:33,2017-11-27 12:44:36,2017-12-08 00:00:00
8,5adf08e34b2e993982a47070956c5c65,1175e95fb47ddff9de6b2b06188f7e0d,81560,curitiba,PR,1ebeea841c590e86a14a0d7a48e7d062,delivered,2018-01-18 12:35:44,2018-01-18 12:56:32,2018-01-18 23:25:35,2018-01-26 15:17:57,2018-02-20 00:00:00
9,4b7139f34592b3a31687243a302fa75b,9afe194fb833f79e300e37e580171f22,30575,belo horizonte,MG,7433cbcc783205509d66a5260da5b574,delivered,2018-01-08 11:22:34,2018-01-08 11:35:27,2018-01-11 01:00:40,2018-01-13 14:51:55,2018-02-05 00:00:00
10,9fb35e4ed6f0a14a4977cd9aea4042bb,2a7745e1ed516b289ed9b29c7d0539a5,39400,montes claros,MG,8428e578bb1cf839ae26a6b7615502b9,delivered,2017-11-27 17:23:20,2017-11-27 18:01:20,2017-11-28 23:04:41,2017-12-08 22:16:17,2017-12-20 00:00:00
11,5aa9e4fdd4dfd20959cad2d772509598,2a46fb94aef5cbeeb850418118cee090,20231,rio de janeiro,RJ,f86c5ed7048ac10eb88ec21c00f71892,delivered,2018-02-07 11:36:42,2018-02-07 11:55:28,2018-02-08 17:46:32,2018-02-26 12:42:54,2018-03-06 00:00:00
12,b2d1536598b73a9abd18e0d75d92f0a3,918dc87cd72cd9f6ed4bd442ed785235,18682,lencois paulista,SP,83d8f70418eefd96f37b483dff430305,delivered,2017-09-09 09:54:57,2017-09-09 10:10:17,2017-09-12 12:42:43,2017-09-20 20:23:34,2017-10-02 00:00:00
13,eabebad39a88bb6f5b52376faec28612,295c05e81917928d76245e842748184d,5704,sao paulo,SP,852d2f4d37773bcbc21c8e09a05a4ea5,delivered,2018-03-07 15:57:14,2018-03-07 16:15:30,2018-03-12 23:02:49,2018-03-15 00:46:30,2018-03-19 00:00:00
14,1f1c7bf1c9b041b292af6c1c4470b753,3151a81801c8386361b62277d7fa5ecf,95110,caxias do sul,RS,6c949e670b5d33dc8fb8ad25b6da4860,delivered,2018-04-01 18:59:31,2018-04-02 17:55:19,2018-04-03 19:33:13,2018-04-13 15:11:21,2018-04-24 00:00:00
15,206f3129c0e4d7d0b9550426023f0a08,21f748a16f4e1688a9014eb3ee6fa325,13412,piracicaba,SP,eac76692452422620996fe5e1a7f8bb0,delivered,2018-01-29 20:32:08,2018-01-29 21:13:27,2018-02-03 00:09:40,2018-02-08 17:03:53,2018-02-22 00:00:00
16,a7c125a0a07b75146167b7f04a7f8e98,5c2991dbd08bbf3cf410713c4de5a0b5,22750,rio de janeiro,RJ,72bab69c50432c6f94d8b50a5f84b69a,delivered,2018-08-13 23:45:05,2018-08-13 23:55:13,2018-08-15 12:11:00,2018-08-17 20:03:08,2018-08-30 00:00:00
17,c5c61596a3b6bd0cee5766992c48a9a1,b6e99561fe6f34a55b0b7da92f8ed775,7124,guarulhos,SP,ec28553b12bef4b538e5d7454464a1c6,delivered,2018-06-18 13:34:21,2018-06-18 13:55:47,2018-06-19 15:07:00,2018-06-21 20:15:28,2018-07-03 00:00:00
18,9b8ce803689b3562defaad4613ef426f,7f3a72e8f988c6e735ba118d54f47458,5416,sao paulo,SP,17825f24877a9289214c301ae0c9424b,delivered,2017-05-11 13:48:47,2017-05-13 11:55:16,2017-05-15 15:30:02,2017-06-07 12:02:14,2017-05-30 00:00:00
19,49d0ea0986edde72da777f15456a0ee0,3e6fd6b2f0d499456a6a6820a40f2d79,68485,pacaja,PA,ab797176e01c2fa3d13aa1fe3e63d9ee,delivered,2017-11-01 21:54:10,2017-11-01 22:06:00,2017-11-06 15:43:02,2017-12-02 01:09:29,2017-12-12 00:00:00
20,154c4ded6991bdfa3cd249d11abf4130,e607ede0e63436308660236f5a52da5e,88034,florianopolis,SC,830d8b3e6875ef6165ffc33219ab4fea,delivered,2017-08-13 10:03:36,2017-08-13 10:24:04,2017-08-14 18:43:45,2017-08-19 12:37:49,2017-09-20 00:00:00
21,690172ab319622688d3b4df42f676898,a96d5cfa0d3181817e2b946f921ea021,74914,aparecida de goiania,GO,aaff8afa47c8426e414a6d908a97713c,delivered,2017-10-15 11:08:48,2017-10-15 11:25:49,2017-10-16 21:36:29,2017-10-25 22:30:58,2017-11-06 00:00:00
22,2938121a40a20953c43caa8c98787fcb,482441ea6a06b1f72fe9784756c0ea75,5713,sao paulo,SP,0198c71148c2e08c7c52b860f640fa4e,delivered,2018-05-08 06:34:07,2018-05-09 04:31:29,2018-05-10 18:12:00,2018-05-18 18:49:30,2018-05-29 00:00:00
23,237098a64674ae89babdc426746260fc,4390ddbb6276a66ff1736a6710205dca,82820,curitiba,PR,eac4ffbe456464bdc3ce5f001b6439c5,delivered,2017-04-14 11:24:56,2017-04-14 11:35:23,2017-04-17 10:43:50,2017-04-20 17:04:51,2017-05-10 00:00:00
24,cb721d7b4f271fd87011c4c83462c076,a5844ba4bfc8d0cc61d13027c7e63bcc,8225,sao paulo,SP,6cdc131d3c28253cd03cd0fbc3d5f938,delivered,2018-05-16 13:04:22,2018-05-16 13:19:29,2018-05-17 15:06:00,2018-05-24 15:16:41,2018-06-05 00:00:00
25,f681356046d9fde60e70c73a18d65ea2,5f102dd37243f152aec3607970aad100,9121,santo andre,SP,daf946e879dab6e7e6b3f968297c3fe3,delivered,2018-02-09 13:46:04,2018-02-09 14:08:53,2018-02-14 23:35:06,2018-02-15 22:41:29,2018-02-23 00:00:00
26,167bd30a409e3e4127df5a9408ebd394,9c0096673baf55453a50073f12d1a37f,74310,goiania,GO,d10eafa208521dc30796e6a26099b6a6,delivered,2018-07-14 10:53:11,2018-07-14 11:05:18,2018-07-17 17:32:00,2018-07-25 16:28:33,2018-08-08 00:00:00
27,6e359a57a91f84095cc64e1b351aef8c,2e6a42a9b5cbb0da62988694f18ee295,4571,sao paulo,SP,a8f5a2b22f55e0af45b300929d1fdc7d,delivered,2017-05-15 17:58:25,2017-05-15 18:10:18,2017-05-16 15:41:37,2017-05-19 11:10:11,2017-06-06 00:00:00
28,e0eea8f69a457b3f1fa246e44c9ebefd,4d221875624017bc47b4d1ce7314a5b7,29311,cachoeiro de itapemirim,ES,3a6d41a4fe7a8e841b7c8e4b77d4e301,delivered,2017-11-24 11:29:52,2017-11-24 13:33:05,2017-11-27 21:12:51,2017-12-06 22:37:09,2017-12-18 00:00:00
29,e3109970a3fe8021d5ff82c577ce5606,a8654e2af5da6bb72f52c22b164855e1,5528,sao paulo,SP,0330631bdb2ec8c341f487ed9c22fc8b,delivered,2018-05-25 12:02:08,2018-05-26 02:31:54,2018-05-29 15:41:00,2018-06-07 22:42:02,2018-06-26 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
99411,da37711b17efd5f2539e8196ab215f04,5f2971f9805e3ccb030226e30c8e8390,4313,sao paulo,SP,c8203bb57639618630affac9e8e923dd,delivered,2017-03-27 23:04:18,2017-03-27 23:23:38,2017-03-28 14:18:59,2017-03-30 17:06:19,2017-04-13 00:00:00
99412,6fb4f2354f36e554ac80141e9128f528,3cc6f2e1b9199837fabb35ff4bf24884,99043,passo fundo,RS,ab042583eff2cb1ffe2110a95da95d4b,delivered,2018-01-22 12:02:21,2018-01-22 14:19:01,2018-01-24 14:36:32,2018-02-07 21:22:40,2018-02-22 00:00:00
99413,6928be51d9496f1aab5da8f15a21aba6,6667649dc575c65058507349be078d4f,13630,pirassununga,SP,5a630e3d4aeb6fca86404481eb19cfe7,delivered,2017-12-14 09:06:34,2017-12-14 10:14:22,2017-12-18 22:29:20,2017-12-27 17:42:05,2018-01-09 00:00:00
99414,eabf770240659f7a6d09b11f12f10f89,065b9e6198f11dbdf7fc1250f9e08afc,19905,ourinhos,SP,9524a52b2633d2f96da98b947c60a4de,delivered,2017-11-08 12:41:52,2017-11-08 13:30:46,2017-11-14 16:08:53,2017-11-21 18:57:38,2017-12-14 00:00:00
99415,184e0c2cfc746789643521df0e9ff904,c64ede6d0ae8901b1b6fb03528c1b7e6,68660,sao miguel do guama,PA,45b3000bcd10464ac178f32cd783fc83,delivered,2017-12-07 23:55:46,2017-12-09 23:50:32,2017-12-11 20:29:02,2018-01-05 17:59:38,2018-01-22 00:00:00
99416,c156d63bdfce1d456bd43cf1c4dadfca,e5cf9da72b751849b7b217f7a943d0fa,9060,santo andre,SP,98484b32a3bbf287f3347e001275ed21,delivered,2018-07-21 08:04:54,2018-07-21 08:24:16,2018-07-23 11:58:00,2018-07-24 17:17:30,2018-07-31 00:00:00
99417,b7c889215de76857c7967c1011125d2d,522e244a96d13876c5bac4985a8d5075,82410,curitiba,PR,1a9543c90f188e2e4fb14327ad4a9c9b,delivered,2018-01-30 15:28:21,2018-01-31 15:30:30,2018-02-16 16:28:33,2018-03-16 20:03:53,2018-03-13 00:00:00
99418,30c96385d694acb8aa2dc0df1770120b,b96d6a178adbabf269fd843b37327798,26112,belford roxo,RJ,357b4b724bbf34f1d64b1c5dfdc88120,delivered,2018-01-24 02:22:12,2018-01-24 15:57:52,2018-01-26 21:28:37,2018-02-07 17:42:55,2018-02-22 00:00:00
99419,a1b5ca506b592bb72d4caadcbfe71385,c811311629fd3d76f5ca5eeb2abfa7e8,17511,marilia,SP,65f3d65b89d1fdde15dc314858c9c161,delivered,2017-04-10 00:08:56,2017-04-10 01:02:42,2017-04-10 12:33:22,2017-04-15 08:13:25,2017-05-02 00:00:00
99420,be631308cb609ff74d0e0fb54815e18c,1c137fe37df712015f6488edafe8ece4,36255,aracitaba,MG,b7ae7c643ef9274727f48dcb0ba08593,delivered,2017-01-25 16:51:27,2017-01-27 11:50:24,2017-01-30 16:22:11,2017-02-08 08:38:49,2017-03-06 00:00:00
99421,5eef6cce1f34954c9e7004332388ccc7,5a1680640123fc80e801301a2fb57395,11045,santos,SP,9bb5771c04f059c10c1f9783fe164d90,delivered,2018-03-13 20:31:59,2018-03-15 03:29:29,2018-03-16 23:15:49,2018-03-23 02:47:48,2018-03-29 00:00:00
99422,821a7275a08f32975caceff2e08ea262,046470763123d3d6364f89095b4e47ab,5734,sao paulo,SP,49645a8902c1ba980836b7bff991d69f,delivered,2018-04-04 17:50:52,2018-04-04 18:08:41,2018-04-05 16:36:49,2018-04-06 23:32:21,2018-04-18 00:00:00
99423,c6ece8a5137f3c9c3a3a12302a19a2ac,aaf22868003377e859049dcf5f0b3fdf,1323,sao paulo,SP,52b783557d95971d0b42195e6bacdc68,delivered,2017-10-20 07:16:27,2017-10-20 07:28:14,2017-10-23 19:13:38,2017-10-24 17:03:38,2017-11-01 00:00:00
99424,e5ed7280cd1a3ac2ba29fd6650d8867c,206e64e8af2633a2ebe158a7fcb860db,8560,poa,SP,53cbf33b674d602f6746cb90a9d874fd,delivered,2017-05-15 17:42:38,2017-05-16 03:25:20,2017-05-16 16:02:08,2017-05-22 14:14:45,2017-06-05 00:00:00
99425,0a7db3996b88954c7aa763b5dd621d5b,15637b62dfa4c5a9df846b22beef0994,52090,recife,PE,d8b354d53fff40dcc80a7e64dbfc2878,delivered,2018-02-13 18:20:51,2018-02-13 18:30:31,2018-02-14 20:22:56,2018-03-29 20:26:42,2018-03-15 00:00:00
99426,935993f47af1ed7d0715c26b686341c5,4452b8ef472646c4cc042cb31a291f3b,12236,sao jose dos campos,SP,e86b1b2dd48839d7351406434afb578d,delivered,2017-11-25 00:31:20,2017-11-25 02:33:11,2017-11-27 18:24:54,2017-12-04 21:13:10,2017-12-20 00:00:00
99427,592b8900e0e8325027d885e6d30d0283,57c2cfb4a80b13ed19b5fb258d29c19d,15720,palmeira d'oeste,SP,60c9450e414b5c1a71cf9034cd62ae29,delivered,2018-06-29 21:32:12,2018-06-29 21:50:36,2018-07-02 14:24:00,2018-07-06 14:27:49,2018-07-24 00:00:00
99428,ffa6d90c36a9c7004692ca50761c69d6,874c93d867b18eb09a5e2f071ee89458,13140,paulinia,SP,2816b0ec050fb4a136c32a6bda007a91,delivered,2017-03-27 16:26:18,2017-03-27 16:35:19,2017-03-29 16:27:26,2017-04-04 13:57:53,2017-04-19 00:00:00
99429,1ed0c832c2dd99570a59260e71768bdf,82d46759af0369aad49084bacf85a6c3,37610,bom repouso,MG,51c6d2f460589fa7b65f2da51e860206,delivered,2017-11-14 12:04:09,2017-11-14 12:15:25,2017-11-27 20:44:47,2017-12-19 19:37:33,2017-12-12 00:00:00
99430,27b9b32173455ef32167540451749d0b,277490f0d435b602fe4475d4b89e9181,6727,cotia,SP,326c29ec5b89834b17aea7d85302fd70,delivered,2017-05-24 11:54:31,2017-05-25 02:50:25,2017-05-26 16:12:26,2017-06-02 14:12:38,2017-06-14 00:00:00
99431,be842c57a8c5a62e9585dd72f22b6338,ca186065de6e2d01cfc99763e6d62048,99150,marau,RS,75c3993b743335fa57b1645f056b59d2,delivered,2018-06-05 13:33:19,2018-06-06 02:55:19,2018-06-07 12:39:00,2018-06-13 16:56:28,2018-07-23 00:00:00
99432,f255d679c7c86c24ef4861320d5b7675,d111b06b6f3a2add0d2241325f65b5ca,13500,rio claro,SP,ca978d2459ea2c5ef6d5fde02be26b9c,delivered,2018-03-06 09:16:56,2018-03-06 09:29:07,2018-03-06 18:51:58,2018-03-07 20:58:53,2018-03-19 00:00:00
99433,14308d2303a3e2bdf4939b86c46d2679,e7f8760e2bbd2f1986bebd99596c088e,66033,belem,PA,ec3a75fb0ac595e461765d2d854b1d08,delivered,2017-03-15 21:04:08,2017-03-15 21:04:08,2017-03-20 08:34:12,2017-04-05 11:07:12,2017-04-26 00:00:00
99434,f5a0b560f9e9427792a88bec97710212,b3e53d18a997f27a3ffd16da497eaf58,7790,cajamar,SP,97d6c1727b0d36b8d04035e35d86f40f,delivered,2018-05-18 21:42:33,2018-05-18 21:55:14,2018-06-04 16:03:00,2018-06-05 19:33:24,2018-06-06 00:00:00
99435,7fe2e80252a9ea476f950ae8f85b0f8f,4b5820135d360a45552b5163835b1d89,35500,divinopolis,MG,c9aea907527f5d4f5fb44955c18a79fb,delivered,2017-12-17 23:13:41,2017-12-18 00:17:27,2017-12-20 18:52:08,2018-01-04 13:08:05,2018-01-23 00:00:00
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,2018-04-13 20:06:37,2018-04-25 00:00:00
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,2018-04-11 18:54:45,2018-04-20 00:00:00
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17,2018-05-09 19:03:15,2018-05-02 00:00:00
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,2017-11-16 19:58:39,2017-12-05 00:00:00
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19 14:27:23,2017-12-19 18:50:39,2017-12-21 19:17:21,2017-12-26 18:42:36,2018-01-08 00:00:00

In [32]:
customer_order_df.shape

(99441, 12)

In [33]:
len(customer_order_df['customer_id'].unique())

99441

In [34]:
len(customer_order_df['customer_unique_id'].unique())

96096